/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Bartłomiej Osak' at '29.05.17 00:59' with Gradle 2.14.1
 *
 * @author Bartłomiej Osak, @date 29.05.17 00:59
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
