/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Bartłomiej Osak' at '26.05.17 19:48' with Gradle 2.14.1
 *
 * @author Bartłomiej Osak, @date 26.05.17 19:48
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
